# Generated by Django 2.0.2 on 2018-02-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0002_currency_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AddField(
            model_name='aggregatedprice',
            name='confidence',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aggregatedprice',
            name='number_of_providers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aggregatedprice',
            name='standard_deviation',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
