# Generated by Django 2.0.2 on 2018-02-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0005_auto_20180214_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_aggregator.Currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_aggregator.Provider')),
            ],
        ),
    ]
