# Generated by Django 2.0.2 on 2018-02-14 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0006_providerfailure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=10, default=0, max_digits=25)),
                ('update_by', models.DateTimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_aggregator.Currency')),
            ],
        ),
        migrations.RemoveField(
            model_name='providerfailure',
            name='currency',
        ),
        migrations.AddField(
            model_name='provider',
            name='cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerfailure',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerresponse',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_aggregator.Provider'),
        ),
    ]
