# Generated by Django 2.0.2 on 2018-02-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0009_remove_currency_supported_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedprice',
            name='used_responses',
            field=models.ManyToManyField(to='price_aggregator.ProviderResponse'),
        ),
    ]
