# Generated by Django 2.0.2 on 2018-09-02 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0012_provider_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_aggregator.Currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_aggregator.Provider')),
            ],
        ),
    ]
