# Generated by Django 2.0.2 on 2018-09-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0013_providerblacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuMarketMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_maker_price', models.DecimalField(decimal_places=10, default=1, max_digits=25)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_aggregator.Currency')),
            ],
        ),
        migrations.AlterModelOptions(
            name='aggregatedprice',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterModelOptions(
            name='providerresponse',
            options={'ordering': ['-date_time']},
        ),
    ]
