# Generated by Django 2.0.2 on 2018-09-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0015_auto_20180918_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='numarketmaker',
            name='market_movement',
            field=models.DecimalField(decimal_places=5, default=0, help_text='The percentage movement that each increment will affect. Set to negative for downward movement', max_digits=25),
        ),
        migrations.AlterField(
            model_name='numarketmaker',
            name='currency',
            field=models.ForeignKey(help_text='The currency to affect', on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='price_aggregator.Currency'),
        ),
        migrations.AlterField(
            model_name='numarketmaker',
            name='market_maker_price',
            field=models.DecimalField(decimal_places=10, default=1, help_text='the price to use in aggregation calculations', max_digits=25),
        ),
        migrations.AlterField(
            model_name='numarketmaker',
            name='market_target',
            field=models.DecimalField(decimal_places=10, default=1, help_text='The target to reach during increments.If market_maker_price and this are equal, no more increments will take place', max_digits=25),
        ),
        migrations.AlterField(
            model_name='numarketmaker',
            name='multiplier',
            field=models.ForeignKey(blank=True, help_text='if this is set the market_maker_price will be multiplied by the latest aggregated price for this currency before being used in Aggregation Calculations. This effectively changes the market_maker_price to apply to this currency, while still being priced in USD', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiplier', to='price_aggregator.Currency'),
        ),
    ]
