# Generated by Django 2.0.2 on 2018-10-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0016_auto_20180918_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedprice',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
