# Generated by Django 2.0.2 on 2018-10-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0017_auto_20181031_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerresponse',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
