# Generated by Django 2.0.2 on 2019-05-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0018_auto_20181031_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerresponse',
            name='market_value',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
    ]
