# Generated by Django 2.0.2 on 2019-05-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0019_providerresponse_market_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerresponse',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
    ]
