# Generated by Django 2.0.2 on 2019-05-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0020_providerresponse_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerresponse',
            name='parent_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='price_aggregator.ProviderResponse'),
        ),
    ]
