# Generated by Django 2.0.2 on 2019-08-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0021_providerresponse_parent_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedprice',
            name='aggregated_price',
            field=models.DecimalField(db_index=True, decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='aggregatedprice',
            name='providers',
            field=models.DecimalField(db_index=True, decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='providerresponse',
            name='value',
            field=models.DecimalField(db_index=True, decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='providerresponse',
            name='volume',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=10, max_digits=25, null=True),
        ),
    ]
