# Generated by Django 2.0.2 on 2019-11-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0022_auto_20190816_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='exchange_provider',
            field=models.BooleanField(default=False),
        ),
    ]
