# Generated by Django 2.0.2 on 2019-11-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0023_provider_exchange_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerresponse',
            name='update_by',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='providerresponse',
            name='value',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='providerresponse',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
    ]
