# Generated by Django 2.2.7 on 2020-04-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_aggregator', '0024_auto_20191109_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_aggregator.Currency')),
                ('high_provider_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_provider_response', to='price_aggregator.ProviderResponse')),
                ('low_provider_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_provider_response', to='price_aggregator.ProviderResponse')),
            ],
        ),
    ]
